### ISSUE TITLE
How I can I use it with view pager or with recyler to show stories like in instagram .

### ISSUE THREAD

**Issue by dinesh750** [bolaware/momentz#2]
This is for just one user.Lets say i have a list of user with different stories just like instagram .In that case how I can handle it.

**Comment by bolaware** [comment]
Have you tried putting it in a recyclerview and didnt work?

**Comment by dinesh750** [comment]
Yes, I have a list like this List<List<String>> itemList and onNextCalled method index is increamented by 2.

**Comment by muhibpirani** [comment]
Does this view work with recyclerview? I'm always getting empty views inside recyclerview/ viewpager
