### ISSUE TITLE
how to use it with java ?

### ISSUE THREAD

**Issue by yung-esco** [bolaware/momentz#3]
hi, i want to know where to take the third parameter to pass to the Momentz constructor when i work with java

**Comment by Farrukh946** [comment]
This is how i am using it in java in my activity class.
`new Momentz(this, momentsList, container, this, R.drawable.story_progress_drawable).start();`

First Param: **this**, your activity context.

Second Param: **momentsList**, your MomentzView List 
`List<MomentzView> momentsList = new ArrayList<>();`

Third Param: **container**, Create a layout in you activity layout having id container and pass that layout here `@BindView(R.id.container) RelativeLayout container;`

Fourth Param: **this**, Momentz Callback implement on your activity 
`AppCompatActivity implements MomentzCallback`

Fifth Param: **R.drawable.story_progress_drawable**, Your story progress drawable resource
`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@android:id/background"
        android:gravity="center_vertical|fill_horizontal">
        <shape
            android:shape="rectangle"
            android:tint="#80DCDCDC">
            <corners android:radius="@dimen/_4sdp" />
            <size android:height="@dimen/_2sdp" />
            <solid android:color="#80DCDCDC" />
        </shape>
    </item>
    <item
        android:id="@android:id/progress"
        android:gravity="center_vertical|fill_horizontal">
        <scale android:scaleWidth="100%">
            <selector>
                <item
                    android:drawable="@android:color/transparent"
                    android:state_enabled="false" />
                <item>
                    <shape
                        android:shape="rectangle"
                        android:tint="@color/explore_select">
                        <corners android:radius="@dimen/_4sdp" />
                        <size android:height="@dimen/_2sdp" />
                        <solid android:color="@color/explore_select" />
                    </shape>
                </item>
            </selector>
        </scale>
    </item>
</layer-list>`
