### ISSUE TITLE
Can't play video propely

### ISSUE THREAD

**Issue by manojyadav983** [bolaware/momentz#8]
I added this code and image loaded from the internet is working fine. but sometimes it skips the view to next view either video view or imageview.
Same in video view the the video loaded sometimes fine but if there are more then one video view in sequence it shows the popup video can't play.Please resolve this issue as soon as possible. Over all it seems good .i need to use in my project.
![device-2020-03-12-185002](https://user-images.githubusercontent.com/33479205/76525642-9d6ce500-6442-11ea-8390-96df79e3d3b8.png)

**Comment by bolaware** [comment]
Fixed
